TAPPING_TERM = 0.14
TAPPING_TERM_FORCE_HOLD = True

MOUSEKEY_CONFIG = {
    "DELAY": 0.05,
    "INTERVAL": 0.02,
    "MAX_SPEED": 40,
    "TIME_TO_MAX": 10,
    "WHEEL_MAX_SPEED": 3,
    "WHEEL_TIME_TO_MAX": 10,
}

